### ISSUE TITLE
Gulp - Unable to cache a config file for v8flags

### ISSUE THREAD

**Issue by huston8** [js-cli/js-v8flags#22] opened 2015-06-11 16:38 UTC
Hello,

I am using a CMS to publish Gulp+less files. The gulp needs to run locally on the CMS server (.\node_modules\.bin\gulp). This works fine if I run via  a command prompt by navigating to \node_modules\.bin. Please note that Gulp is not installed globally on server.

However when I am trying to run gulp with help of C# template (CMD + arguements = "/c CD node_modules/.bin/ & gulp")  I get the below error.

Engine: Error in Engine.Transform
Engine: Error in Engine.Transform
D:\t20150611182707811\node_modules\gulp\node_modules\liftoff\index.js:182
      throw err;
            ^
Error: EPERM, open 'C:\Windows\system32\config\systemprofile\.v8flags.3.28.73.W655$.json'

Unable to cache a config file for v8flags to a your home directory
or a temporary folder. To fix this problem, please correct your
environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
NOTE: the user running this must be able to access provided path.
If all else fails, please open an issue here:
http://github.com/tkellen/js-v8flags

Unable to cache a config file for v8flags to a your home directory
or a temporary folder. To fix this problem, please correct your
environment by setting HOME=/path/to/home or TEMP=/path/to/temp.
NOTE: the user running this must be able to access provided path.
If all else fails, please open an issue here:
http://github.com/tkellen/js-v8flags
    at Error (native)

Liftoff Version is v2.1.0:

**Comment by thesbros** [comment] 2015-06-11 21:29
This looks like a permission error. It looks like the HOME environment variable is set to system32\config, and the user probably doesn't have permission to write to there.

**Comment by huston8** [comment] 2015-06-12 08:39
I dont see the home variable is set on server. what can be other issues?

**Comment by thesbros** [comment] 2015-06-12 08:42
Open the node REPL with `node`, and type in the following commands:
```
console.log(env.USERPROFILE || env.HOMEDRIVE + env.HOMEPATH || env.HOME || null);
console.log(os.tmpdir());
```

And reply with the output.

**Comment by huston8** [comment] 2015-06-12 08:47
The strange thing is, this works with command prompt, but not when I run a command prompt using C#.

Here is the output:

> console.log(env.USERPROFILE || env.HOMEDRIVE + env.HOMEPATH || env.HOME || null);
ReferenceError: env is not defined
    at repl:1:13
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
> console.log(os.tmpdir());
C:\Users\SDL_W6~1\AppData\Local\Temp\2
undefined
>

**Comment by thesbros** [comment] 2015-06-12 08:49
Oh sorry, try:
```js
console.log(process.env.USERPROFILE);
console.log(process.env.HOMEPATH);
console.log(process.env.HOMEDRIVE);
console.log(process.env.HOME);
```

**Comment by huston8** [comment] 2015-06-12 08:55
Here you go:

> console.log(os.tmpdir());
C:\Users\SDL_W6~1\AppData\Local\Temp\2
undefined

> console.log(process.env.USERPROFILE);
C:\Users\SDL_W655_W662
undefined

> console.log(process.env.HOMEPATH);
\Users\SDL_W655_W662
undefined

> console.log(process.env.HOMEDRIVE);
C:
undefined

> console.log(process.env.HOME);
undefined
undefined

**Comment by thesbros** [comment] 2015-06-12 08:56
The variables seem to be fine in the CLI. Does this "C# template" change users? You could try putting the commands I listed in a .js file, and then run it through the template to see what it outputs.

**Comment by huston8** [comment] 2015-06-12 09:11
I am not very sure how can i do this as we have a class library project. However looking at the code it does not change the users.

**Comment by thesbros** [comment] 2015-06-12 09:13
Well, it's doing something with the environment variables. If you can do this in the code, try setting the environment variable HOME to a place where the config file can be written before gulp is run.

**Comment by huston8** [comment] 2015-06-12 09:24
I came across this line of code : 

 string user = System.Security.Principal.WindowsIdentity.GetCurrent().Name;

and it returns "NT AUTHORITY\\NETWORK SERVICE".

This might be the issue?

**Comment by thesbros** [comment] 2015-06-12 20:01
Yes that's probably the issue. Is there a way to change the user to what it should be?

**Comment by huston8** [comment] 2015-06-13 18:30
Thats indeed the issue. As a workaround I manually gave read/write permissions to  'Network Service'  user on directory 'C:\Windows\system32\config\'. I understand this shall not be a permanent solution. 

All tridion templates run via impersonated user 'Network Service' hence it will be difficult for us to change that. Is there any way the 'C:\Windows\system32\config\' directory can be replaced by another one?

**Comment by thesbros** [comment] 2015-06-13 19:39
Yes, you can set the `USERPROFILE` variable to the path you want it to save to, as long as the template doesn't override it.

**Comment by huston8** [comment] 2015-06-14 10:59
Thanks Oden. Sorry, but I am new to this gulp and all. Could you please advise how can I set this variable? 
Do you mean to say that this should be set in environment variables of server?

**Comment by thesbros** [comment] 2015-06-14 19:25
Yes, the environment variables of the server. Though, the template may override it.

**Comment by huston8** [comment] 2015-06-15 14:17
I added Something like this to System Variables:
variable Name : USERPROFILE
Variable Value : D:\gulp-test\

But this isn't working. I dont think the template overrides either.....

**Comment by artyfarty** [comment] 2015-06-15 15:54
FFS.

Our builds **suddenly** failed because of that cryptic .cache error. Simply created folder myself and it worked. Why does it not create that folder itself?

Now why change this in minor version (that is not locked in gulp for some stupid reason)?

**Comment by tkellen** [comment] 2015-06-15 15:57
@artyfarty Sorry for the regression. I'll release a patch that reverts this.

@phated What do you think about just throwing an annoying warning in gulp if this file can't be cached, and allowing it to just run anyway? For CI servers (where this seems to be the most error prone) the performance hit of having to invoke node to get the v8 flag listing should be meaningless.

**Comment by phated** [comment] 2015-06-15 19:45
@tkellen :+1: on that idea. any way to bubble that up to a liftoff event so gulp can format the warning nicely?

**Comment by huston8** [comment] 2015-07-30 15:02
Hello....any update on this one....affecting now on another server :(

**Comment by phated** [comment] 2015-07-30 19:09
@huston8 all of us are busy currently with work and other life things, sorry. If you can, please send a patch.

**Comment by raffus** [comment] 2015-08-31 19:04
I wonder how can a collaborator give such "contribution". 

PHATED, instead of loosing your time writing this crap please use it to cooperate.
Lots of people having this issue, including me.

Any patch available or new release in a near future?

**Comment by phated** [comment] 2015-08-31 19:07
@raffus PRs welcome

**Comment by raffus** [comment] 2015-08-31 19:12
?

**Comment by ilikebits** [comment] 2015-11-30 11:56
:+1:  This issue hits me whenever I try to build with `gulp` on hosted servers where I don't have write permissions for `$HOME`.

**Comment by banerjs** [comment] 2015-12-17 07:20
+1

Just hit this issue trying to deploy on OpenShift

**Comment by ilikebits** [comment] 2015-12-21 20:00
@banerjs Just pushed 2.0.11 which should allow you to deploy. Can you see if this fixes your problem?

**Comment by banerjs** [comment] 2015-12-22 02:33
Although I am now using Heroku in order to have more flexibility with my node versions (packages can sometimes be so finicky!), I just pushed to OpenShift and can confirm that I no longer see the permissions issue that caused me to post here a few days ago.

Thanks!

**Comment by ilikebits** [comment] 2015-12-22 02:43
Awesome, closing this issue.

**Closed by ilikebits** 2015-12-22 02:43 UTC

**Comment by victorguo** [comment] 2016-03-29 06:22
Hi, I came across the error as following:

> EXEC : error : ENOENT: no such file or directory, open 'C:\Users\SVC-ZH~1.BLD\AppData\Local\Temp\.v8flags.4.6.85.31.prod\svc-zhu.uca.bld.json'

.v8flags.4.6.85.31.**prod\svc-zhu.uca.bld**.json is not a valid name in Windows so it fails to create the config file.

Just let you know that I am running TFS 2015 build servers...And I trigger my build remotely. I guess that is why the username turns out **prod\svc-zhu.uca.bld** instead of **svc-zhu.uca.bld**. ("prod" is the domain name)

Can someone help me out of this?

**Comment by tkellen** [comment] 2016-03-29 21:28
Whatcha think about md5 hashing the username @phated?

**Comment by phated** [comment] 2016-03-29 21:51
@tkellen I'd be fine with that, I think

**Comment by phated** [comment] 2016-03-29 21:53
@tkellen does that break current installs?

**Comment by tkellen** [comment] 2016-03-29 21:53
It wouldn't break current installs, it would just regen the temp file on the next run.

**Comment by victorguo** [comment] 2016-04-06 02:48
@tkellen  Sorry to be rude but any plans to make the change?

**Comment by phated** [comment] 2016-04-06 04:52
@victorguo all of us are completely booked.  feel free to submit a PR and we can try to find time to review it.
